server:
  port: 8888

spring:
  profiles:
    active: local
  application:
    name: backend
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DanielKosmin/application-configs
          token: ${ACCESS_TOKEN}
          clone-on-start: true
